defaults: &defaults
  blog:
    blog_name: 没有船的海贼
  neat_setting: 24
  awesome_setting: <%= "Did you know 5+5 = #{5+5}" %>
  messages:

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
